# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CCACHE=/usr/bin/ccache
CXX=/usr/bin/gcc
CC=/usr/bin/gcc
MXX=/usr/bin/gcc
AS=/usr/bin/gcc
MM=/usr/bin/gcc

SH=/usr/bin/g++
AR=/usr/bin/ar
LD=/usr/bin/g++


gb28181-server_CXXFLAGS=-m64 -g -std=c++11 -I. -I/usr/local/include -O0 -Wall -g2 -ggdb
gb28181-server_CXXFLAGS=-m64 -g -std=c++11 -I. -I/usr/local/include -O0 -Wall -g2 -ggdb
gb28181-server_LDFLAGS=-m64 -L/usr/local/lib -lpthread -losip2 -losipparser2 -leXosip2

default:  gb28181-server

all:  gb28181-server

.PHONY: default all  gb28181-server

gb28181-server: build/.objs/gb28181-server/linux/x86_64/debug/src/utils/json_helper.cpp.o build/.objs/gb28181-server/linux/x86_64/debug/src/utils/helper.cpp.o build/.objs/gb28181-server/linux/x86_64/debug/src/utils/singleton.cpp.o build/.objs/gb28181-server/linux/x86_64/debug/src/event_handler/register_handler.cpp.o build/.objs/gb28181-server/linux/x86_64/debug/src/main.cpp.o build/.objs/gb28181-server/linux/x86_64/debug/src/server.cpp.o
	@echo linking.debug gb28181-server
	@mkdir -p .
	$(VV)$(LD) -o gb28181-server build/.objs/gb28181-server/linux/x86_64/debug/src/utils/json_helper.cpp.o build/.objs/gb28181-server/linux/x86_64/debug/src/utils/helper.cpp.o build/.objs/gb28181-server/linux/x86_64/debug/src/utils/singleton.cpp.o build/.objs/gb28181-server/linux/x86_64/debug/src/event_handler/register_handler.cpp.o build/.objs/gb28181-server/linux/x86_64/debug/src/main.cpp.o build/.objs/gb28181-server/linux/x86_64/debug/src/server.cpp.o $(gb28181-server_LDFLAGS)

build/.objs/gb28181-server/linux/x86_64/debug/src/utils/json_helper.cpp.o: src/utils/json_helper.cpp
	@echo ccache compiling.debug src/utils/json_helper.cpp
	@mkdir -p build/.objs/gb28181-server/linux/x86_64/debug/src/utils
	$(VV)$(CXX) -c $(gb28181-server_CXXFLAGS) -o build/.objs/gb28181-server/linux/x86_64/debug/src/utils/json_helper.cpp.o src/utils/json_helper.cpp

build/.objs/gb28181-server/linux/x86_64/debug/src/utils/helper.cpp.o: src/utils/helper.cpp
	@echo ccache compiling.debug src/utils/helper.cpp
	@mkdir -p build/.objs/gb28181-server/linux/x86_64/debug/src/utils
	$(VV)$(CXX) -c $(gb28181-server_CXXFLAGS) -o build/.objs/gb28181-server/linux/x86_64/debug/src/utils/helper.cpp.o src/utils/helper.cpp

build/.objs/gb28181-server/linux/x86_64/debug/src/utils/singleton.cpp.o: src/utils/singleton.cpp
	@echo ccache compiling.debug src/utils/singleton.cpp
	@mkdir -p build/.objs/gb28181-server/linux/x86_64/debug/src/utils
	$(VV)$(CXX) -c $(gb28181-server_CXXFLAGS) -o build/.objs/gb28181-server/linux/x86_64/debug/src/utils/singleton.cpp.o src/utils/singleton.cpp

build/.objs/gb28181-server/linux/x86_64/debug/src/event_handler/register_handler.cpp.o: src/event_handler/register_handler.cpp
	@echo ccache compiling.debug src/event_handler/register_handler.cpp
	@mkdir -p build/.objs/gb28181-server/linux/x86_64/debug/src/event_handler
	$(VV)$(CXX) -c $(gb28181-server_CXXFLAGS) -o build/.objs/gb28181-server/linux/x86_64/debug/src/event_handler/register_handler.cpp.o src/event_handler/register_handler.cpp

build/.objs/gb28181-server/linux/x86_64/debug/src/main.cpp.o: src/main.cpp
	@echo ccache compiling.debug src/main.cpp
	@mkdir -p build/.objs/gb28181-server/linux/x86_64/debug/src
	$(VV)$(CXX) -c $(gb28181-server_CXXFLAGS) -o build/.objs/gb28181-server/linux/x86_64/debug/src/main.cpp.o src/main.cpp

build/.objs/gb28181-server/linux/x86_64/debug/src/server.cpp.o: src/server.cpp
	@echo ccache compiling.debug src/server.cpp
	@mkdir -p build/.objs/gb28181-server/linux/x86_64/debug/src
	$(VV)$(CXX) -c $(gb28181-server_CXXFLAGS) -o build/.objs/gb28181-server/linux/x86_64/debug/src/server.cpp.o src/server.cpp

clean:  clean_gb28181-server

clean_gb28181-server: 
	@rm -rf gb28181-server
	@rm -rf gb28181-server.sym
	@rm -rf build/.objs/gb28181-server/linux/x86_64/debug/src/utils/json_helper.cpp.o
	@rm -rf build/.objs/gb28181-server/linux/x86_64/debug/src/utils/helper.cpp.o
	@rm -rf build/.objs/gb28181-server/linux/x86_64/debug/src/utils/singleton.cpp.o
	@rm -rf build/.objs/gb28181-server/linux/x86_64/debug/src/event_handler/register_handler.cpp.o
	@rm -rf build/.objs/gb28181-server/linux/x86_64/debug/src/main.cpp.o
	@rm -rf build/.objs/gb28181-server/linux/x86_64/debug/src/server.cpp.o

