// 此文件用于http接口测试 基于vscode中的REST Client插件
@url=http://10.23.132.54:18080
@header=Content-Type:application/json

### 查询设备信息
get {{url}}/query_device

### 开始推流
get {{url}}/start_rtsp_publish?device=34020000002000001001

### 停止推流
get {{url}}/stop_rtsp_publish?device=34020000002000001001

### 开启对讲 start_invite_talk
get {{url}}/start_invite_talk?device=34020000002000001001

### 结束对讲
#get {{url}}/stop_talk?device=34020000002000001001

### 播放鉴权
#post {{url}}/on_play